name: appointments_api
description: Dart package which manages the appointments domain.
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  authentication_api:
    path: ../authentication_api
  category_api:
    path: ../category_api
  geoflutterfire:
    path: ../GeoFlutterFire
  user_api:
    path: ../user_api
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  firebase_storage: ^8.0.0
  freezed_annotation: ^0.14.0
  geolocator: ^7.0.1
  intl: ^0.17.0
  meta: ^1.3.0
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  freezed: ^0.14.0+1
  json_serializable: ^4.0.2
  mockito: ^5.0.0
